# Generated by Django 3.1.2 on 2021-02-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('parent', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('parentNodeId', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
    ]
