# Generated by Django 3.1.2 on 2021-02-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_idgen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_idgen',
            },
        ),
    ]
