# Generated by Django 3.1.2 on 2021-02-06 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_tbl_idgen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_idgen',
        ),
    ]
