# Generated by Django 3.1.2 on 2021-02-06 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_tbl_idgen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='userId',
        ),
    ]
