# Generated by Django 3.1.2 on 2021-02-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_tbl_user_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_idgen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_idgen',
            },
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='userId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
