# Generated by Django 3.1.2 on 2021-02-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20210206_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='userImage',
        ),
    ]
