# Generated by Django 3.1.2 on 2021-02-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_tbl_user_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='userImage',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
